version: '3'

services:
  object-detection:
    image: vision/detection:latest
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 5000:5000
