version: '2'

services:
  # Service for vision object detection
  detection:
    image: bildeord:latest
    volumes:
      - ./bildeord:/code
    ports:
      - '5000:5000'
    # Ensures container to be kept alive and does not exit.
    tty: true
