version: "3.8"

services:

  # Nginx HTTP web server
  web:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./:/www/code
      - ./config/nginx.conf:/etc/nginx/config.d/default.conf
    ports:
      - 80:80  # HTTP Protocol port
    depends_on:
      - flask

  # App service for model
  flask:
    build:
      context: "."
      dockerfile: Dockerfile
    image: bildeord:latest
    container_name: bildeord
    # command: make run
    volumes:
      - ./:/webapp/code
    env_file:
      - ./env/.env.development  # note sure about this too much
    # networks:
    #   flask-net:
    #     aliases:
    #       - backend

networks:
  flask-net: